### ISSUE TITLE
IOS Use of undeclared identifier 'WXApi'

### ISSUE THREAD

**Issue by ynqq** [little-snow-fox/react-native-wechat-lib#1]
大佬您好 iOS引入这一块之后 会找不到WXApi 这个应该怎么解决
` - (BOOL)application:(UIApplication *)application handleOpenURL:(NSURL *)url {
    return  [WXApi handleOpenURL:url delegate:self];
}

- (BOOL)application:(UIApplication *)application
  continueUserActivity:(NSUserActivity *)userActivity
  restorationHandler:(void(^)(NSArray<id<UIUserActivityRestoring>> * __nullable
  restorableObjects))restorationHandler {
  return [WXApi handleOpenUniversalLink:userActivity
  delegate:self];
}`

**Comment by little-snow-fox** [comment]
因为你没引入 WXApi.h 文件，请在 AppDelegate.h 头部加上 #import "WXApi.h"

**Comment by RodgerLai** [comment]
@little-snow-fox 加上 #import "WXApi.h"后提示   'WXApi.h' file not found
现在要手动加  'WXApi.h' ？  如果能把最新用法体现在playground就很棒了

**Comment by RodgerLai** [comment]
@little-snow-fox 而且使用注册函数registerApp会报错：Cannot read property 'registerApp' of undefined

**Comment by little-snow-fox** [comment]
@RodgerLai 确实，我应该把 react-native link react-native-wechat-lib 也写到文档里面。

**Comment by kingsofish** [comment]
我确实使用了react-native link react-native-wechat-lib，但是在appdelegate #import "WXApi.h"还是报'WXApi.h' file not found，我用的是0.55版本，没有使用pod，用的是手动导入依赖到xcode中

**Comment by kingsofish** [comment]
> 我确实使用了react-native link react-native-wechat-lib，但是在appdelegate #import "WXApi.h"还是报'WXApi.h' file not found，我用的是0.55版本，没有使用pod，用的是手动导入依赖到xcode中

不知道为什么link了不成功，手动添加到header  search paths就好了
