### ISSUE TITLE
ios:授权登录 RCTWeChat不执行onResp回调（通过universal link ）

### ISSUE THREAD

**Issue by songzuyun** [little-snow-fox/react-native-wechat-lib#11]
我现在把RCTWeChat类改写成单例，并暴露一个对象方法（实现是onResp的代码），然后在AppDelegate的onResp里调用这个对象方法，暂时可实现效果

**Comment by little-snow-fox** [comment]
好的，我会在下一个版本修复该问题

**Comment by wlsy** [comment]
目前在iOS上确实是如果使用universal link 登录的时候没有返回内容

**Comment by little-snow-fox** [comment]
是的，因为 object-c 代码没把回调事件通知到 js 层面

**Comment by songzuyun** [comment]
实际上我已经解决这个问题了
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray<id<UIUserActivityRestoring>> * _Nullable))restorationHandler
{
    //触发回调方法
    [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
    return [WXApi handleOpenUniversalLink:userActivity delegate:self];
}

**Comment by little-snow-fox** [comment]
这段代码在文档上就已经说明需要添加了，[IOS doc](https://github.com/little-snow-fox/react-native-wechat-lib/blob/master/docs/build-setup-ios.md)

**Comment by wlsy** [comment]
会有计划在什么时候发布新版本解决这个问题么？或者有什么临时的方式可以处理这个

**Comment by little-snow-fox** [comment]
@wlsy 预计这个周末会修复该问题。

**Comment by little-snow-fox** [comment]
@wlsy 你好，已经确定授权功能并没有任何问题，如果出现无法接受授权成功后的返回，请你根据配置文档重新检查你的配置，特别是上面提到的这段代码 [code](https://github.com/little-snow-fox/react-native-wechat-lib/issues/11#issuecomment-564423256)

**Comment by little-snow-fox** [comment]
<img width="857" alt="截屏2019-12-22下午1 50 01" src="https://user-images.githubusercontent.com/23468639/71317838-bf4d7000-24c2-11ea-8ce0-14174e35afb0.png">

**Comment by wlsy** [comment]
> 这段代码在文档上就已经说明需要添加了，[IOS doc](https://github.com/little-snow-fox/react-native-wechat-lib/blob/master/docs/build-setup-ios.md)
这里面的文档跟


> 实际上我已经解决这个问题了
> 
> * (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray<id> * _Nullable))restorationHandler
>   {
>   //触发回调方法
>   [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
>   return [WXApi handleOpenUniversalLink:userActivity delegate:self];
>   }

这两个代码不一样

**Comment by KingAmo** [comment]
是的，需要加上
```
[RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];

```

**Comment by little-snow-fox** [comment]
@KingAmo 谢谢提醒，我把这句代码添加到说明文档上了
