### ISSUE TITLE
微信分享，跳转问题

### ISSUE THREAD

**Issue by Evan-Future** [little-snow-fox/react-native-wechat-lib#118]
IOS版本中，分享图片和文章时来回跳转2次，第一次从APP跳转到微信会显示链接中...，然后从微信跳回APP，然后再自动从APP跳转到微信，此时才时正常的分享操作。
Android版本中正常

**Comment by little-snow-fox** [comment]
出现这个问题无非就是你的 universalLink 配置有误，文档中已经说明会出现这个问题了 [universalLink doc](https://github.com/little-snow-fox/react-native-wechat-lib/blob/master/docs/build-setup-ios.md#2-then-copy-the-following-in-appdelegatem)

**Comment by little-snow-fox** [comment]
出现这种问题请检查你的 Universal Links 是否配置正常，link 域名是否能解析到你的服务器，详细文档请到 [apple](https://developer.apple.com/ios/universal-links) 官网查阅

**Comment by Evan-Future** [comment]
> 出现这种问题请检查你的 Universal Links 是否配置正常，link 域名是否能解析到你的服务器，详细文档请到 [apple](https://developer.apple.com/ios/universal-links) 官网查阅

这个应该在IOS的安装文档中进行标注明确，最好是有一个外链教程也可以，往往小白们不是太清楚Universal Links的影响

**Comment by Evan-Future** [comment]
> 出现这种问题请检查你的 Universal Links 是否配置正常，link 域名是否能解析到你的服务器，详细文档请到 [apple](https://developer.apple.com/ios/universal-links) 官网查阅
按照Universal Links的配置方式配了，还是不行，Universal Links中的网址内容有什么要求吗？

**Comment by Evan-Future** [comment]
> 出现这种问题请检查你的 Universal Links 是否配置正常，link 域名是否能解析到你的服务器，详细文档请到 [apple](https://developer.apple.com/ios/universal-links) 官网查阅
按照Universal Links的配置方式配了，还是不行，Universal Links中的网址内容有什么要求吗？

**Comment by Evan-Future** [comment]
> 出现这种问题请检查你的 Universal Links 是否配置正常，link 域名是否能解析到你的服务器，详细文档请到 [apple](https://developer.apple.com/ios/universal-links) 官网查阅
按照Universal Links的配置方式配了，还是不行，Universal Links中的网址内容有什么要求吗？

**Comment by Evan-Future** [comment]
> 出现这种问题请检查你的 Universal Links 是否配置正常，link 域名是否能解析到你的服务器，详细文档请到 [apple](https://developer.apple.com/ios/universal-links) 官网查阅

按照Universal Links的配置方式配了，还是不行，Universal Links中的网址内容有什么要求吗？

**Comment by little-snow-fox** [comment]
请问你直接在 Safari 浏览器打开 Universal Links 链接的时候能正常跳转到你的 app 吗？

**Comment by Evan-Future** [comment]
> 请问你直接在 Safari 浏览器打开 Universal Links 链接的时候能正常跳转到你的 app 吗？

没有相关显示，是否跟网站内容有关？我从苹果官方验证了下链接是有问题的，但是已经按照要求放了apple-app-site-association文件，也可以访问

**Comment by little-snow-fox** [comment]
@Evan-Future 如果你在 Safari 访问 Universal Links 都不能跳转到 app，那说明你的配置有问题，请检查一下 xcode 上面配置的地址是否一致，和 apple-app-site-association 文件里面的配置项是否有误，具体请参考苹果官网或其他相关教程，这方便的配置确实有些繁琐

**Comment by Evan-Future** [comment]
> 请问你直接在 Safari 浏览器打开 Universal Links 链接的时候能正常跳转到你的 app 吗？

我把apple-app-site-association文件放在了官方说的.well-known子文件夹是ok的，根目录不行，不过这样子做，感觉使用时有卡顿，这个是因为每次调用时候的时候都会去检测apple-app-site-association的合法性吗？

**Comment by Evan-Future** [comment]
> @Evan-Future 如果你在 Safari 访问 Universal Links 都不能跳转到 app，那说明你的配置有问题，请检查一下 xcode 上面配置的地址是否一致，和 apple-app-site-association 文件里面的配置项是否有误，具体请参考苹果官网或其他相关教程，这方便的配置确实有些繁琐

如果是在手机的搜索中输入的网址直接点击用Safari打开是可以打开App的，但是打开Safari后输入网址是不会在网页中有打开提示的，这个可能是我操作上的理解问题。仅供大家参考，希望别误解了Safari的访问跳转到App的方式

**Comment by little-snow-fox** [comment]
据我所知，这个过程是有缓存机制的，并不会每次打开都去访问你的服务器，但具体运作原理，可能只有苹果自己知道了。或者，你可以提交一个测试版试下实际效果

**Comment by Evan-Future** [comment]
> 据我所知，这个过程是有缓存机制的，并不会每次打开都去访问你的服务器，但具体运作原理，可能只有苹果自己知道了。或者，你可以提交一个测试版试下实际效果

经过测试得出结论：首先必须在APP第一次调用微信前准备好域名下的验证文件apple-app-site-association，然后再第一次打开出现连接中...，后续就不会有了，原因是APP会在调用微信时做域名的验证文件获取，后续除非是有变更时才会重新请求验证文件。亲测有效。如果还是不行检查必要的设置和验证文件的格式及内容是否相符，然后可以尝试重新卸载APP后重装尝试即可解决。如果还是不行一定是设置或者验证文件的访问有问题导致
