### ISSUE TITLE
安卓配置报错

### ISSUE THREAD

**Issue by xuexiangzhe** [little-snow-fox/react-native-wechat-lib#13]
include ':RCTWeChat'
project(':RCTWeChat').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-wechat/android')
依照安卓文档中加入这个链接，会报这个错误
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :RCTWeChat.
Show Details
Affected Modules: app

如果将上面的链接换成
include ':RCTWeChat'
project(':RCTWeChat').projectDir = new File(rootProject.projectDir, '../node_modules/**react-native-wechat-lib**/android')

会报这个错误
ROR: The modules ['node_modules-react-native-wechat-lib-android-RCTWeChat', 'node_modules-react-native-wechat-lib-android-react-native-wechat-lib~1'] point to the same directory in the file system.
Each module must have a unique path.

同样react-native-wechat这个库也是会报这个错误，在react-native-wechat库中提了issue，应该是么有回复了，求帮忙看一下

**Comment by little-snow-fox** [comment]
@xuexiangzhe 请提供下你的 rn 版本号

**Comment by xuexiangzhe** [comment]
> @xuexiangzhe 请提供下你的 rn 版本号

0.61.5

**Comment by xuexiangzhe** [comment]
> @xuexiangzhe 请提供下你的 rn 版本号

解决了，把这两段代码删掉，重新编译就可以了
include ':RCTWeChat'
project(':RCTWeChat').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-wechat/android')

dependencies {
  implementation project(':RCTWeChat') // Add this line
}

**Comment by gatspy** [comment]
0.60+不需要手动link了, 直接按照[文档](https://github.com/little-snow-fox/react-native-wechat-lib/blob/master/docs/build-setup-android.md) 配置Activity就可以了.

**Comment by xuexiangzhe** [comment]
已解决
