### ISSUE TITLE
rn60以上可以用吗?

### ISSUE THREAD

**Issue by taoqf** [little-snow-fox/react-native-wechat-lib#14]
老板有没有测试过在react-native60及以上版本可以正常使用吗?
求证一下.

**Comment by little-snow-fox** [comment]
你好，我就是在rn60.5版本开发本库，如果你遇到问题，请提供详细报错信息或者截图，我会进行处理。

**Comment by taoqf** [comment]
@little-snow-fox 多谢回复.`sendAuthRequest`调用闪退.
```ts
try {
	await WeChat.sendAuthRequest('snsapi_userinfo', 'teststate');
} catch (error) {
	console.error(error);
}
```
连catch也不会走.
app注册过`registerApp`.可以`shareText`.这应该说明注册是成功了的,但`sendAuthRequest`闪退,怀疑是参数的问题,但appid没有问题,微信也审核过.现在搞不清楚是哪里的问题,希望老板能帮忙分析一下.

**Comment by taoqf** [comment]
```json
{
"react": "16.11.0",
"react-native": "0.61.5"
}
```
以上为我用的版本号,其它版本我也试过,一样的问题.

**Comment by little-snow-fox** [comment]
麻烦你检查一下你的 Schema 配置 [IOS doc](https://github.com/little-snow-fox/react-native-wechat-lib/blob/master/docs/build-setup-ios.md)

**Comment by Xiapeixu** [comment]
> 麻烦你检查一下你的 Schema 配置 [IOS doc](https://github.com/little-snow-fox/react-native-wechat-lib/blob/master/docs/build-setup-ios.md)

android上闪退

**Comment by little-snow-fox** [comment]
@Xiapeixu 我会在今天内抽时间检查下该问题

**Comment by AlexKitCoder** [comment]
react-native-wechat 安卓在rn 0.61.4上存在闪退，分享正常（不点击取消分享的情况下，点击取消分享照样闪退），又辗转来到你这个库，看到更新日期以为有戏，然而还是闪退，能拉起授权界面，点击同意就闪退了，期待作者更新

**Comment by LuDongWei** [comment]
我们微信想用新的sdk，发现 react-native-wechat   转战到 react-native-wechat-lib 使用碰到问题，希望寻求组织的帮助，要哭了

**Comment by AlexKitCoder** [comment]
> 我们微信想用新的sdk，发现 react-native-wechat 转战到 react-native-wechat-lib 使用碰到问题，希望寻求组织的帮助，要哭了

是啊，现在基本上用的都是rn 0.61.4  0.61.5左右，目前市面可供选择只有react-native-wechat，但是那个库安卓在该版本上存在闪退问题，如果这个库能解决授权的闪退，分享（取消的）闪退问题就好了

**Comment by little-snow-fox** [comment]
你好，我将会在今天内检查下安卓上是否存在该问题，如果存在，我会优先解决它。

------------------------------------------------------------------
发件人：Alex-黑白 <notifications@github.com>
发送时间：2019年12月24日(星期二) 11:23
收件人：little-snow-fox/react-native-wechat-lib <react-native-wechat-lib@noreply.github.com>
抄　送：snowfox <fox@sfxh.cc>; Mention <mention@noreply.github.com>
主　题：Re: [little-snow-fox/react-native-wechat-lib] rn60以上可以用吗? (#14)

我们微信想用新的sdk，发现 react-native-wechat 转战到 react-native-wechat-lib 使用碰到问题，希望寻求组织的帮助，要哭了
是啊，现在基本上用的都是rn 0.61.4 0.61.5左右，目前市面可供选择只有react-native-wechat，但是那个库安卓在该版本上存在闪退问题，如果这个库能解决授权的闪退，分享（取消的）闪退问题就好了

**Comment by taoqf** [comment]
看来出现这问题的不止我一个呀

**Comment by AlexKitCoder** [comment]
> 看来出现这问题的不止我一个呀

坐等作者更新，估计很多移植库的都是在mac上做rn开发，基本上都是优先保障的ios，android问题估计容易被忽略；

**Comment by AlexKitCoder** [comment]
> 你好，我将会在今天内检查下安卓上是否存在该问题，如果存在，我会优先解决它。
> […](#)
> ------------------------------------------------------------------ 发件人：Alex-黑白 <notifications@github.com> 发送时间：2019年12月24日(星期二) 11:23 收件人：little-snow-fox/react-native-wechat-lib <react-native-wechat-lib@noreply.github.com> 抄　送：snowfox <fox@sfxh.cc>; Mention <mention@noreply.github.com> 主　题：Re: [little-snow-fox/react-native-wechat-lib] rn60以上可以用吗? (#14) 我们微信想用新的sdk，发现 react-native-wechat 转战到 react-native-wechat-lib 使用碰到问题，希望寻求组织的帮助，要哭了 是啊，现在基本上用的都是rn 0.61.4 0.61.5左右，目前市面可供选择只有react-native-wechat，但是那个库安卓在该版本上存在闪退问题，如果这个库能解决授权的闪退，分享（取消的）闪退问题就好了 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，安卓继续做了测试，发现分享好友，选择回到app会重新打开app；分享朋友圈会直接闪退（但是分享会成功），授权登录，能拉起授权界面，点击同意闪退，安卓目前的问题大致是这三个闪退问题。

**Comment by little-snow-fox** [comment]
@AlexKitCoder 这种情况似乎是微信无法回调APP导致，你先检查下你的配置，我晚上会详细处理。

**Comment by AlexKitCoder** [comment]
> @AlexKitCoder 这种情况似乎是微信无法回调APP导致，你先检查下你的配置，我晚上会详细处理。

你好，找到问题了哈，你的库没问题，是我那个wxapi文件夹路径和package的路径导致的，用android studio打开package路径都红色的，改后不会闪退了，且能拿到正确授权，分享也都没问题了

**Comment by taoqf** [comment]
@AlexKitCoder ???可以说得清楚些吗?我这里现在也有这问题呀,不知道是不是跟你一样的问题

**Comment by AlexKitCoder** [comment]
> @AlexKitCoder ???可以说得清楚些吗?我这里现在也有这问题呀,不知道是不是跟你一样的问题

比如项目为 com.aaa.bbb;
我之前闪退是因为在项目里面调用了WXEntryActivity，而路径问题导致找不到这个class；用android studio跑得时候看日志发现的，我的WXEntryActivity类放在wxapi这个文件夹，之前我的类放在了com.wxapi这儿，和bbb同级的，正确做法是全部放在com.aaa.bbb下面，然后WXEntryActivity这个类文件的package路径为com.aaa.bbb.wxapi;这样分享，授权都不闪退了

**Comment by Xiapeixu** [comment]
> > @AlexKitCoder ???可以说得清楚些吗?我这里现在也有这问题呀,不知道是不是跟你一样的问题
> 
> 比如项目为 com.aaa.bbb;
> 我之前闪退是因为在项目里面调用了WXEntryActivity，而路径问题导致找不到这个class；用android studio跑得时候看日志发现的，我的WXEntryActivity类放在wxapi这个文件夹，之前我的类放在了com.wxapi这儿，和bbb同级的，正确做法是全部放在com.aaa.bbb下面，然后WXEntryActivity这个类文件的package路径为com.aaa.bbb.wxapi;这样分享，授权都不闪退了

根据你提供的方法我试了一下,确实是不闪退了,但是授权没有返回数据啊

**Comment by little-snow-fox** [comment]
@Xiapeixu 请检查下安卓文档上面的这段代码
```java
package your.package.wxapi;

import android.app.Activity;
import android.os.Bundle;
import com.theweflex.react.WeChatModule;

public class WXEntryActivity extends Activity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    WeChatModule.handleIntent(getIntent());
    finish();
  }
}
```

**Comment by oMhuAaN** [comment]
火钳留名

**Comment by little-snow-fox** [comment]
经过检查，sendAuthRequest 在安卓9上面运行良好，没有报错，我的RN版本为60.5。
<img width="411" alt="截屏2019-12-25上午6 32 49" src="https://user-images.githubusercontent.com/23468639/71426161-c05be880-26e0-11ea-8590-a1cf1419e848.png">
<img width="887" alt="截屏2019-12-25上午6 29 57" src="https://user-images.githubusercontent.com/23468639/71426164-c3ef6f80-26e0-11ea-842a-a2672a96f169.png">

**Comment by Xiapeixu** [comment]
现在好了
