### ISSUE TITLE
ios 微信支付报WeChat API invoke returns false

### ISSUE THREAD

**Issue by chenweigh** [little-snow-fox/react-native-wechat-lib#142]
```
WeChat.pay(payload)
      .then((res) => {
        console.log('支付成功：',res);
      })
      .catch((err) => {
        console.log('支付失败：', err);
      });
```
微信分享是成功的，支付报 `WeChat API invoke returns false.`
如何解决呢？也按照文档配置完整了。只不过没有订阅支付回调事件

**Comment by marlti7** [comment]
> ```
> WeChat.pay(payload)
>       .then((res) => {
>         console.log('支付成功：',res);
>       })
>       .catch((err) => {
>         console.log('支付失败：', err);
>       });
> ```
> 
> 微信分享是成功的，支付报 `WeChat API invoke returns false.`
> 如何解决呢？也按照文档配置完整了。只不过没有订阅支付回调事件

你解决了吗 我也是这样

**Comment by chenweigh** [comment]
检查一下payload参数的拼写
```
let payload = {
            appId: response.appid,
            partnerId: response.partnerid,
            prepayId: response.prepayid,
            nonceStr: String(response.noncestr),
            timeStamp: response.timestamp,
            package: response.package,
            sign: response.sign,
          };
```
如果前端确认字段的key没错的话，那么让服务器按照微信官方文档检查一下所生成各种参数是否有错？

**Comment by q4wen** [comment]
你们解决了吗？我看源码并不需要填appId

**Comment by marlti7** [comment]
> 你们解决了吗？我看源码并不需要填appId

不需要appId

**Comment by chenweigh** [comment]
解决了，问题在于sdk中传值参数的大小写不对发自我的华为手机
