### ISSUE TITLE
For logged in wechat in android, sendAuthRequest could not invoke wechat. But for new installed (not login) wechat, sendAuthRequest could invoke wechat 

### ISSUE THREAD

**Issue by dongdyang** [little-snow-fox/react-native-wechat-lib#148]
在真机上测试的，对于安卓，如果是刚下载的微信，用sendAuthRequest是可以激活wechat；但是如果是已经登录的微信，sendAuthRequest不能激起微信。

谢谢作者看这个issue

**Comment by GGGODLIN** [comment]
相同問題

**Comment by dongdyang** [comment]
做了两个改动就修复了这个问题：
1、添加universal link在项目里
2、在微信开发者平台上的app_id不同，这个需要用release之后的app，用来generate app key。这个key在开发者里的mobile app填错了，之前填的development环境下的app key
