### ISSUE TITLE
请问，怎样将现有项目从不带lib的版本，切换到这个带lib的版本？

### ISSUE THREAD

**Issue by oMhuAaN** [little-snow-fox/react-native-wechat-lib#15]
如果从零开始一个新项目，需要怎么配置，只看这个库就可以吗？是否需要结合不带lib的版本的文档。

**Comment by oMhuAaN** [comment]
其实【起步】这个步骤，我看得不是很明白，求一对小白白更加友好的详细文档

**Comment by oMhuAaN** [comment]
具体说来，您这个【起步】里面的文档是【书接上回】还是【从零开始】？

**Comment by oMhuAaN** [comment]
从不带lib的版本，切换到这个带lib的版本。是否只需要先yarn remove再yarn add就行？

**Comment by little-snow-fox** [comment]
lib 是根据 react-native-wechat 重写开发，大部分调用的方法都不一样，不如早就合并了，目前这个库并不打算兼容使用了 react-native-wechat 的老项目。
你需要重写按照 lib 的接口文档重新调用相关接口。
起步文档的话，你需要根据文档看看哪里漏配置了自行补上。

**Comment by little-snow-fox** [comment]
你好，lib 是根据 react-native-wechat 重写开发，大部分调用的方法都不一样，不然早就合并了，目前这个库并不打算兼容使用了 react-native-wechat 的老项目。
你需要重新按照 lib 的接口文档重新调用相关接口。
起步文档的话，你需要根据文档看看哪里漏配置了自行补上。
