### ISSUE TITLE
Android授权登录后，返回原APP显示白屏（不清楚是没返回还是返回了白屏，后台显示是返回了）

### ISSUE THREAD

**Issue by suxinying** [little-snow-fox/react-native-wechat-lib#159]
表现：
能够正常调微信，授权登录后（或分享后点击返回原App表现也一样），返回原App显示白屏页面
AndroidManifest已配置taskAffinity
![image](https://user-images.githubusercontent.com/34708049/115826663-d6e19380-a43d-11eb-9e30-0c15eafb9334.png)
微信端包名也是一致的
```
const loginByWechat = async () => {
    const isInstalled = await WeChat.isWXAppInstalled();
    if (isInstalled) {
      const result = await WeChat.sendAuthRequest('snsapi_userinfo');
      console.error(result);
    }
  };
```
也不能接收到任何回调或者错误

**Comment by FarmersReact** [comment]
相同的问题，希望作者能看下
