### ISSUE TITLE
LaunchMiniProgram is not a function

### ISSUE THREAD

**Issue by oMhuAaN** [little-snow-fox/react-native-wechat-lib#17]
C:\work\testTiaoXiaoChengXv\node_modules\react-native\Libraries\YellowBox\YellowBox.js:71 Possible Unhandled Promise Rejection (id: 0):
TypeError: WeChat.LaunchMiniProgram is not a function
TypeError: WeChat.LaunchMiniProgram is not a function

**Comment by oMhuAaN** [comment]
![图片](https://user-images.githubusercontent.com/24907600/71439250-d3e46f00-2733-11ea-936a-811e18251f88.png)

**Comment by oMhuAaN** [comment]
可以分享文本，不能拉起小程序。不知道怎么回事，要哭了。。

**Comment by oMhuAaN** [comment]
![图片](https://user-images.githubusercontent.com/24907600/71439886-38a0c900-2736-11ea-987c-43976bbac83e.png)

**Comment by little-snow-fox** [comment]
请提供你的设备信息和RN版本。

**Comment by oMhuAaN** [comment]
![图片](https://user-images.githubusercontent.com/24907600/71440284-a5689300-2737-11ea-8d3f-d873ac91173f.png)

**Comment by oMhuAaN** [comment]
设备是坚果pro2，
![图片](https://user-images.githubusercontent.com/24907600/71440355-d9dc4f00-2737-11ea-91ca-b3c8bf51b235.png)

**Comment by little-snow-fox** [comment]
请检查你的安装包签名，还有检查一下微信开放平台(不是公众平台)上，是否已经绑定要跳转的小程序。

**Comment by oMhuAaN** [comment]
签名正确
包名正确

**Comment by oMhuAaN** [comment]
后端说已经确定绑定了

**Comment by oMhuAaN** [comment]
![图片](https://user-images.githubusercontent.com/24907600/71440600-a6e68b00-2738-11ea-87e5-b50e80a3a3fd.png)

**Comment by oMhuAaN** [comment]
![图片](https://user-images.githubusercontent.com/24907600/71440687-13618a00-2739-11ea-94e9-a6f4cc633b1a.png)

**Comment by KingAmo** [comment]
您好，能帮忙看看#18吗？ 你iOS端集成成功了吗

**Comment by oMhuAaN** [comment]
![图片](https://user-images.githubusercontent.com/24907600/71440705-2f652b80-2739-11ea-9870-5150f72d6693.png)

**Comment by oMhuAaN** [comment]
> 
> 
> 您好，能帮忙看看 #18 吗？ 你iOS端集成成功了吗

我没有ios端，

**Comment by oMhuAaN** [comment]
![图片](https://user-images.githubusercontent.com/24907600/71440750-5d4a7000-2739-11ea-87f7-7cbdfb080446.png)

**Comment by oMhuAaN** [comment]
![图片](https://user-images.githubusercontent.com/24907600/71440763-69363200-2739-11ea-93ac-cb38e11d9931.png)

**Comment by little-snow-fox** [comment]
之前装过 react-native-wechat 码？

**Comment by oMhuAaN** [comment]
> 
> 
> 之前装过 react-native-wechat 吗？

装过，

**Comment by oMhuAaN** [comment]
补充一下，系统win10，

**Comment by oMhuAaN** [comment]
刚试了用 npm命令装，结果还是一样

**Comment by oMhuAaN** [comment]
![图片](https://user-images.githubusercontent.com/24907600/71442968-5294d880-2743-11ea-877a-648bfd2b949a.png)

**Comment by oMhuAaN** [comment]
launchMiniProgram，发现开头是小写的l

**Comment by oMhuAaN** [comment]
> 
> 
> 之前装过 react-native-wechat 吗？

发现问题：launchMiniProgram是小写开头的。
