### ISSUE TITLE
微信支付的流程bug

### ISSUE THREAD

**Issue by xiaoxiaodemeng** [little-snow-fox/react-native-wechat-lib#174]
有些手机底层有app分身功能，点击支付，选择那个微信，这个时候关闭弹框之后----拿不到失败回调

**Comment by Su2San** [comment]
大佬这么解决的

**Comment by xiaoxiaodemeng** [comment]
> 大佬这么解决的

太久了，我记得就不支持分身支付。
![image](https://github.com/little-snow-fox/react-native-wechat-lib/assets/30209304/59a8e4b3-0800-47b1-a44b-11fdebd41e43)
这是具体的diff
