### ISSUE TITLE
支援最新微信SDK和React Native TurboModule 新架構

### ISSUE THREAD

**Issue by rickychan0611** [little-snow-fox/react-native-wechat-lib#211]
这小哥开始了新的库，请帮忙测验及完善
repo: [https://github.com/Hector-Chong/native-wechat](https://github.com/Hector-Chong/native-wechat)
doc: [https://native-wechat.hector.im/](https://native-wechat.hector.im/)

**Comment by little-snow-fox** [comment]
是一个好库，年后试下，看看有没我能完善的地方
