### ISSUE TITLE
ios 設置完後，需不需要做任何教程以外的事？

### ISSUE THREAD

**Issue by c78867886** [little-snow-fox/react-native-wechat-lib#22]
我照著教程做了一次 包含`npm install`, `link` 還有 ios的設置
需求只有分享到好友圈
做完教程設定後，每次分享還是一直跳出
`Error: WeChat API invoke returns false.`

我的universal link放的 `https://www.google.com`
我是看作者說可以隨意放，所以就放了這個
然後在微信公開平台上
我也把app 的universal link設置為 `https://www.google.com`

我用了 `WeChat.register("appid",  "https://www.google.com")`
這頁沒有出現問題
但是當用了分享到好友圈時
一直出現 `Error: WeChat API invoke returns false.`
想知道除了教程的步驟外 需要額外設置什麼嗎？
因為我看了微信的SDK文檔 還要設定一些跟universal link有關的設置
(文檔網址: https://developers.weixin.qq.com/doc/oplatform/Mobile_App/Access_Guide/iOS.html)
想知道我們需要自己做那些事情嗎？

**Comment by little-snow-fox** [comment]
你出现的情况与 universal link 没关系，universal link 只是微信拉起你的 APP 所需要的配置。
麻烦你用 xcode 连手机打开调试模式，一般情况下，xcode 会给出错误提示。

**Comment by c78867886** [comment]
> 你出现的情况与 universal link 没关系，universal link 只是微信拉起你的 APP 所需要的配置。
> 麻烦你用 xcode 连手机打开调试模式，一般情况下，xcode 会给出错误提示。

我嘗試一下，之後來回報一下是什麼問題，謝謝！ ：）

**Comment by AlexKitCoder** [comment]
> 你出现的情况与 universal link 没关系，universal link 只是微信拉起你的 APP 所需要的配置。
> 麻烦你用 xcode 连手机打开调试模式，一般情况下，xcode 会给出错误提示。

您好，上次安卓的已经全部可以正常使用，今天调试ios真机，遇到问题了：
xcode报错如下：
ssqagent[24030:6179309] NSURLConnection finished with error - code -1002
2020-01-08 12:04:25.659 [warn][tid:com.facebook.react.JavaScript] Possible Unhandled Promise Rejection (id: 1):
Error: WeChat API invoke returns false.
/private/var/containers/Bundle/Application/05BE62BF-15F2-4976-A9E5-ACDB468571CA/ssqagent.app/main.jsbundle:147355:36
__invokeCallback@/private/var/containers/Bundle/Application/05BE62BF-15F2-4976-A9E5-ACDB468571CA/ssqagent.app/main.jsbundle:2723:23
/private/var/containers/Bundle/Application/05BE62BF-15F2-4976-A9E5-ACDB468571CA/ssqagent.app/main.jsbundle:2418:34
__guard@/private/var/containers/Bundle/Application/05BE62BF-15F2-4976-A9E5-ACDB468571CA/ssqagent.app/main.jsbundle:2635:15
大概就是：Possible Unhandled Promise Rejection (id: 1):
Error: WeChat API invoke returns false.
安卓能正常使用，已经按照文档要求配置：rn0.61.5，ios13.2，iphoneXR真机

**Comment by AlexKitCoder** [comment]
> 你出现的情况与 universal link 没关系，universal link 只是微信拉起你的 APP 所需要的配置。
> 麻烦你用 xcode 连手机打开调试模式，一般情况下，xcode 会给出错误提示。

作者您好，我使用ios真机调试，也遇到了同样的问题， WeChat API invoke returns false;  是发生在全局注册的时候，当时返回了true；但接下来就报这个错误了，其余的分享，登陆全都用不了，安卓没问题，rn0.61.5；ios13.3；能不能帮帮我呢？

**Comment by little-snow-fox** [comment]
@AlexKitCoder 请检查你的 LSApplicationQueriesSchemes ，可能是因为这个配置存在问题导致无权限访问微信

**Comment by AlexKitCoder** [comment]
> LSApplicationQueriesSchemes

info.plist 已经添加：
<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>weixin</string>
		<string>wechat</string>
		<string>weixinULAPI</string>
	</array>

**Comment by little-snow-fox** [comment]
@AlexKitCoder URL Schema 呢？

**Comment by AlexKitCoder** [comment]
> @AlexKitCoder URL Schema 呢？

xcode进入了info，底部的URL Types添加了identifer ： weixin；URL Schema：填入了安卓上能正常调用的appid

**Comment by AlexKitCoder** [comment]
> @AlexKitCoder URL Schema 呢？

解决了一部分，是那个universalLink的问题，ios register那儿第二个参数把配置的链接填写进去就正常了，安卓不填也可以，目前ios真机登陆没问题了，分享依然报错

**Comment by AlexKitCoder** [comment]
> @AlexKitCoder URL Schema 呢？

抱歉，作者，不是配置的问题，也不是你库的问题，而是我这儿shareLocalImage和shareImage的区别问题哈，我使用了截图，分享图片，截图得到的是本地文件路径，错误的使用了这二者

**Comment by little-snow-fox** [comment]
> > @AlexKitCoder URL Schema 呢？
> 
> 抱歉，作者，不是配置的问题，也不是你库的问题，而是我这儿shareLocalImage和shareImage的区别问题哈，我使用了截图，分享图片，截图得到的是本地文件路径，错误的使用了这二者，安卓好像没有这个区别，两个我都传入了本地文件路径能正常分享，ios好像只能使用前者，抱歉哈

**Comment by little-snow-fox** [comment]
@AlexKitCoder  shareLocalImage 是我特意新加的功能，因为如果使用 shareImage 来分享长截图的话，在 ios 上会出现白屏情况，在安卓上会出现内存溢出。
我先把这个问题关闭，如果有新的问题，请打开一个新的 issues。
