### ISSUE TITLE
iOS WeChat API invoke returns false.

### ISSUE THREAD

**Issue by xhf3332** [little-snow-fox/react-native-wechat-lib#224]
iOS 报错
 [javascript] Possible Unhandled Promise Rejection (id: 3):
Error: WeChat API invoke returns false.
@http://192.168.31.228:8081/index.bundle?platform=ios&dev=true&minify=false:180300:
<img width="685" alt="image" src="https://user-images.githubusercontent.com/75054364/223702032-4481e803-7022-4efb-8dc8-0297722ce03b.png">

**Comment by surethink** [comment]
奇怪，我也是同样的问题。登录没问题

**Comment by little-snow-fox** [comment]
这种情况一般是因为你传递了错误格式的 universalLink 参数导致，如果你实在没 universalLink，你可以填一个 https://baidu.com 进去

**Comment by xhf3332** [comment]
> 这种情况一般是因为你传递了错误格式的 universalLink 参数导致，如果你实在没。universalLink，你可以填一个 https://baidu.com 进去做测试
谢谢。是的。universalLink 链接有点问题。
