### ISSUE TITLE
关于 UIWebView 问题：ITMS-90809

### ISSUE THREAD

**Issue by excitedcat** [little-snow-fox/react-native-wechat-lib#23]
使用命令： `grep -r UIWebView node_modules/*` 之后发现这个包还有 UIWebView 出现

Binary file node_modules/react-native-wechat-lib/ios/libWeChatSDK.a matches

> Dear Developer,We identified one or more issues with a recent delivery for your app, "脸疼" 0.2.3 (55). Your delivery was successful, but you may wish to correct the following issues in your next delivery:ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.After you’ve corrected the issues, you can upload a new binary to App Store Connect.Best regards,The App Store Team

**Comment by little-snow-fox** [comment]
你好，请你检查下是不是其它库导致，或者你使用过 react-native-wechat 库。
本库不可能存在 UIWebView，就连所使用的腾讯 SDK 也声明移除了 UIWebView 使用 WKWebview 代替。
加上我的应用圣诞前才提交过一个新版本给 AppStore 审核，也没收到任何警告文件。

**Comment by excitedcat** [comment]
@little-snow-fox 可能是其他库引起的，不知道这个文件会不会有影响

node_modules/react-native-wechat-lib/ios/libWeChatSDK.a

能否帮我分析下原因，我看了下日志，库文件中有很多包含了 `UIWebView`，源代码中没有找到

```
[wangqian@MacbookPro:faceteng-app]$ grep -r UIWebView node_modules/*
node_modules/create-react-class/node_modules/fbjs/lib/UserAgent.js.flow:   * - UIWebView
node_modules/create-react-class/node_modules/fbjs/lib/UserAgent.js:   * - UIWebView
node_modules/fbjs/lib/UserAgent.js.flow:   * - UIWebView
node_modules/fbjs/lib/UserAgent.js:   * - UIWebView
node_modules/jsc-android/dist/include/JSContextPrivate.h:/*! @abstract The delegate the context will use when trying to load a module. Note, this delegate will be ignored for contexts returned by UIWebView. */
Binary file node_modules/react-native-alipay-u/ios/libAlipaySDK.a matches
Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/ModuleCache.noindex/11EFTSSB0BUOA/UIKit-1V5UHAPTOD24G.pcm matches
Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/ModuleCache.noindex/11EFTSSB0BUOA/modules.idx matches
Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/Index/DataStore/v5/records/EJ/UIWebView.h-17DCX353XRLEJ matches
Binary file node_modules/react-native-gesture-handler/ios/build/RNGestureHandler/Index/DataStore/v5/units/UIKit-1V5UHAPTOD24G.pcm-35LZDCPFUDPTH matches
node_modules/react-native-legacy-components/node_modules/fbjs/lib/UserAgent.js.flow:   * - UIWebView
node_modules/react-native-legacy-components/node_modules/fbjs/lib/UserAgent.js:   * - UIWebView
Binary file node_modules/react-native-mweibo/ios/libWeiboSDK/libWeiboSDK.a matches
Binary file node_modules/react-native-qqsdk/ios/RCTQQSDK/TencentOpenAPI.framework/TencentOpenAPI matches
node_modules/react-native-webview/README.md:- [7.0.1](https://github.com/react-native-community/react-native-webview/releases/tag/v7.0.1) - Removed UIWebView
Binary file node_modules/react-native-wechat-lib/ios/libWeChatSDK.a matches
node_modules/ua-parser-js/test/browser-test.json:        "ua"      : "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Mobile/14A456 QQ/6.5.3.410 V1_IPH_SQ_6.5.3_1_APP_A Pixel/1080 Core/UIWebView NetType/WIFI Mem/26",
```

**Comment by little-snow-fox** [comment]
会出现 UIWebView 关键字是正常的，因为库里面有注释描述移除了 UIWebView，你用 grep 当然会查到相关匹配结果。
你试下 `grep -r [UIWebView node_modules/*` 或者 `grep -r (UIWebView node_modules/* `

**Comment by weishai** [comment]
@little-snow-fox  求助！请问怎么使用不包含支付的微信sdk版本，我2月16日提交的App审核被拒，说有第三方支付代码，让我解释，我实际用不上微信支付的

**Comment by little-snow-fox** [comment]
@weishai 你好，我已经在 #27 问题中给予回复，这个问题我先关闭掉。

**Comment by zj799072102** [comment]
@little-snow-fox Can provide a libWechatSDK.a without uiwebview annotation description?

**Comment by wangxx2026** [comment]
> 你好，请你检查下是不是其它库导致，或者你使用过 react-native-wechat 库。
> 本库不可能存在 UIWebView，就连所使用的腾讯 SDK 也声明移除了 UIWebView 使用 UiKitWebview 代替。
> 加上我的应用圣诞前才提交过一个新版本给 AppStore 审核，也没收到任何警告文件。

我使用过react-native-wechat  这个库，换了react-native-wechat-lib grep -r UIWebView node_modules/* 也没发现，但是提交的审核包还是不行，请教一下回事啥原因呢？
