### ISSUE TITLE
react-native 0.70.6运行报错

### ISSUE THREAD

**Issue by devoutDisciple** [little-snow-fox/react-native-wechat-lib#237]
我按照步骤进行了配置，我复制了 /ios/libWeChatSDK.a 到 Xcode 项目根目录，但是还是提示
<img width="313" alt="image" src="https://user-images.githubusercontent.com/23021082/236499482-7efaa10f-5ba8-489e-b463-dddd2c56070d.png">

"react-native-wechat-lib"版本 "3.0.4"
手机iphone13    ios版本16.3.1

**Comment by ChenlingasMx** [comment]
同样的问题
