### ISSUE TITLE
没有找到 com.wechatlib 包，请问是哪里不对吗？

### ISSUE THREAD

**Issue by doubunv** [little-snow-fox/react-native-wechat-lib#241]
方案1:

1. 参照安装命令执行了 npm install react-native-wechat-lib --save ，同时也尝试了 yarn add react-native-wechat-lib
2. 同时在AndroidManifest.xml 和 build.gradle 都配置了下面的内容
```
<queries>
<package android:name="com.tencent.mm" />
</queries>
```

```
    dependencies {
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
        classpath("com.tencent.mm.opensdk:wechat-sdk-android:+")
    }
```

3. 执行yarn android的时候，错误提示了 
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
/Users/xiaochuan/Docker/www/canpin/APPTest/android/app/src/main/java/com/apptest/wxapi/WXPayEntryActivity.java:5: 错误: 找不到符号
import com.wechatlib;
          ^
  符号:   类 wechatlib
  位置: 程序包 com

我的环境版本如下：

` "react": "18.2.0",
    "react-native": "0.71.3",
    "react-native-linear-gradient": "^2.6.2",
com.android.tools.build:gradle:7.3.1
`

<img width="795" alt="image" src="https://github.com/little-snow-fox/react-native-wechat-lib/assets/20400014/6e9f08a9-cf1a-4e4c-b9b9-464dc38f392e">

我是新手，请问还要配置什么地方吗？谢谢！

**Comment by doubunv** [comment]
问题已经解决了，请大家参考源码包里面的这个文件： node_modules/react-native-wechat-lib/docs/build-setup-android.md

**Comment by ShaoGongBra** [comment]
你是咋解决的呢？

**Comment by showtan001** [comment]
> 你是咋解决的呢？

`xxxx.wxapi;

import android.app.Activity;
import android.os.Bundle;
import com.wechatlib.WeChatLibModule;

public class WXPayEntryActivity extends Activity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    WeChatLibModule.handleIntent(getIntent());
    finish();
  }
}`
