### ISSUE TITLE
RN 0.71, ios正常，安卓编译报错，请问大佬如何解决？

### ISSUE THREAD

**Issue by bobacCurry** [little-snow-fox/react-native-wechat-lib#244]
![image](https://github.com/little-snow-fox/react-native-wechat-lib/assets/54611609/d29f4b8c-7268-4f2d-adf6-62eff65cd1b2)

/Users/alex/Project/MH/android/app/src/main/java/com/mh/wxapi/WXEntryActivity.java:4: 错误: 程序包com.wechatlib不存在
import com.wechatlib.WeChatLibModule;
                    ^
/Users/alex/Project/MH/android/app/src/main/java/com/mh/MainApplication.java:17: 错误: 程序包com.wechatlib不存在
import com.wechatlib.WeChatLibPackage;
                    ^
/Users/alex/Project/MH/android/app/src/main/java/com/mh/wxapi/WXEntryActivity.java:10: 错误: 找不到符号
    WeChatLibModule.handleIntent(getIntent());
    ^
  符号:   变量 WeChatLibModule
  位置: 类 WXEntryActivity
/Users/alex/Project/MH/android/app/src/main/java/com/mh/MainApplication.java:36: 错误: 找不到符号
          packages.add(new WeChatLibPackage());
                           ^
  符号: 类 WeChatLibPackage
注: /Users/alex/Project/MH/android/app/src/debug/java/com/mh/ReactNativeFlipper.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
4 个错误

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 23s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
注: /Users/alex/Project/MH/node_modules/@react-native-camera-roll/camera-roll/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollModule.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: /Users/alex/Project/MH/node_modules/@react-native-camera-roll/camera-roll/android/src/main/java/com/reactnativecommunity/cameraroll/CameraRollPackage.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。
/Users/alex/Project/MH/android/app/src/main/java/com/mh/wxapi/WXEntryActivity.java:4: 错误: 程序包com.wechatlib不存在
import com.wechatlib.WeChatLibModule;
                    ^
/Users/alex/Project/MH/android/app/src/main/java/com/mh/MainApplication.java:17: 错误: 程序包com.wechatlib不存在
import com.wechatlib.WeChatLibPackage;
                    ^
/Users/alex/Project/MH/android/app/src/main/java/com/mh/wxapi/WXEntryActivity.java:10: 错误: 找不到符号
    WeChatLibModule.handleIntent(getIntent());
    ^
  符号:   变量 WeChatLibModule
  位置: 类 WXEntryActivity
/Users/alex/Project/MH/android/app/src/main/java/com/mh/MainApplication.java:36: 错误: 找不到符号
          packages.add(new WeChatLibPackage());
                           ^
  符号: 类 WeChatLibPackage
注: /Users/alex/Project/MH/android/app/src/debug/java/com/mh/ReactNativeFlipper.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
4 个错误

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by bobacCurry** [comment]
我是用的是1.1.27版本![image](https://github.com/little-snow-fox/react-native-wechat-lib/assets/54611609/e3d4c407-935e-4767-bbe1-6ca04e6dde93)

**Comment by little-snow-fox** [comment]
很可能是 gradle 没拉取到 wechatSDK，用为新版本不再引用本地 SDK，而是根据微信官方文档使用 gradle 自动拉取

**Comment by bobacCurry** [comment]
嗯呢，是这个原因，我把引入的包换了就没问题了，您的文档可以备注一下这个情况🫰> 很可能是 gradle 没拉取到 wechatSDK，用为新版本不再引用本地 SDK，而是根据微信官方文档使用 gradle 自动拉取

**Comment by yylingsj** [comment]
> 

包名应该是哪个呢？我也遇到这个问题了。

**Comment by bobacCurry** [comment]
> 

安卓不是加了个文件嘛，wxapi/WXEntryActivity  这个，里面的类 WeChatModule， 用这个包名 com.theweflex.react.WeChatModule 

<img width="638" alt="image" src="https://github.com/little-snow-fox/react-native-wechat-lib/assets/54611609/e673558a-86e8-4b38-bc05-5462b5b921ed">

**Comment by bobacCurry** [comment]
> > 
> 
> 包名应该是哪个呢？我也遇到这个问题了。

**Comment by bobacCurry** [comment]
> > 
> 
> 包名应该是哪个呢？我也遇到这个问题了。

安卓不是加了个文件嘛，wxapi/WXEntryActivity 这个，里面的类 WeChatModule， 用这个包名 com.theweflex.react.WeChatModule

<img width="730" alt="image" src="https://github.com/little-snow-fox/react-native-wechat-lib/assets/54611609/1dcc6c25-4b02-4c71-8494-4298ff116d27">

**Comment by DingTianYi9** [comment]
你好 我IOS 爆这个错误 跟您也是一样 0.71版本 请问您有遇到过吗
<img width="1205" alt="image" src="https://github.com/little-snow-fox/react-native-wechat-lib/assets/50064250/2179f3eb-fec7-458f-9580-05f013223707">

**Comment by bobacCurry** [comment]
> 你好 我IOS 爆这个错误 跟您也是一样 0.71版本 请问您有遇到过吗
> 
> <img width="1205" alt="image" src="https://github.com/little-snow-fox/react-native-wechat-lib/assets/50064250/2179f3eb-fec7-458f-9580-05f013223707">
> 
> 

安装最新的版本就好了

**Comment by DingTianYi9** [comment]
> 

是 3.0.4版本吗 ，我就是用的3.0.4版本 rn版本是0.71.6

**Comment by bobacCurry** [comment]
他的那个包你按照他的要求拷贝进去了吗？

**Comment by bobacCurry** [comment]
> > 
> 
> 
> 
> 是 3.0.4版本吗 ，我就是用的3.0.4版本 rn版本是0.71.6

哦，不好意思，我看错了，我用的 1.1.27 版本

**Comment by DingTianYi9** [comment]
> 

1.1.27我也试了 也是其他的报错，我看issue上面大佬说换成3.0.4就好了，结果是这种错误。明天我再试试1.1.27，大佬你1.1.27IOS支付是可以的吗，感谢回复！

**Comment by DingTianYi9** [comment]
> > > 
> > 
> > 
> > 1.1.27我也试了 也是其他的报错，我看issue上面大佬说换成3.0.4就好了，结果是这种错误。明天我再试试1.1.27，大佬你1.1.27IOS支付是可以的吗，感谢回复！
> 
> 支付我还没测试，1.1.27支付有问题吗？

实际我现在引入这个库，按照作者大大教程配置连编译都没过

**Comment by DingTianYi9** [comment]
> 

嗯嗯 十分感谢！

**Comment by DingTianYi9** [comment]
> 

哥你好，我问下你的IOS AppDelegate.h文件 
![image](https://github.com/little-snow-fox/react-native-wechat-lib/assets/50064250/8e321030-7f43-41dc-9125-2a66883b5db8)
最开始是这样的吗 照着文档配置会变成我下面注释的那样，我才是这个原因导致的我编译不过

**Comment by bobacCurry** [comment]
> > 
> 
> 哥你好，我问下你的IOS AppDelegate.h文件 ![image](https://user-images.githubusercontent.com/50064250/255769059-8e321030-7f43-41dc-9125-2a66883b5db8.png) 最开始是这样的吗 照着文档配置会变成我下面注释的那样，我才是这个原因导致的我编译不过

#import <React/RCTBridgeDelegate.h>
#import <UIKit/UIKit.h>
#import "WXApi.h"

@interface AppDelegate : UIResponder <UIApplicationDelegate, RCTBridgeDelegate, WXApiDelegate>

@property (nonatomic, strong) UIWindow *window;

@end


这是我的配置

**Comment by bobacCurry** [comment]
> #import <React/RCTBridgeDelegate.h>

你看看是不是这个弄错了 #import <React/RCTBridgeDelegate.h>

**Comment by DingTianYi9** [comment]
> 

搞定了 把文档上的 一个UIResponder改成原来项目的就好了
![image](https://github.com/little-snow-fox/react-native-wechat-lib/assets/50064250/4879a9de-869c-4f2a-9573-133ee50a0ded)
测试了下微信支付没问题 ，现在去搞Android了 感谢

**Comment by bobacCurry** [comment]
> > 
> 
> 
> 
> 搞定了 把文档上的 一个UIResponder改成原来项目的就好了
> 
> ![image](https://github.com/little-snow-fox/react-native-wechat-lib/assets/50064250/4879a9de-869c-4f2a-9573-133ee50a0ded)
> 
> 测试了下微信支付没问题 ，现在去搞Android了 感谢

Good 👍

**Comment by erTongWang** [comment]
> > > 
> > 
> > 
> > 包名应该是哪个呢？我也遇到这个问题了。
> 
> 安卓不是加了个文件嘛，wxapi/WXEntryActivity 这个，里面的类 WeChatModule， 用这个包名 com.theweflex.react.WeChatModule
> 
> <img alt="image" width="730" src="https://private-user-images.githubusercontent.com/54611609/251974868-1dcc6c25-4b02-4c71-8494-4298ff116d27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDA4OTksIm5iZiI6MTcwOTU0MDU5OSwicGF0aCI6Ii81NDYxMTYwOS8yNTE5NzQ4NjgtMWRjYzZjMjUtNGIwMi00YzcxLTg0OTQtNDI5OGZmMTE2ZDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA4MjMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNjg2ODA3YThjY2VmNWM1MWYyY2E3MmI3MTI2ZGZkYjQwN2Y1MDhlMTI0ODk2ZmY4OWUzMmI1NjRiNDIwY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bVrZBOKyyALEXWaHy8ziKSFKDuoI19TfPX8_kYRtxQs">

按照这个配置之后还是报错，楼主的意思是要把react-native-wechat-lib 这个库升级到3.0.4吗
