### ISSUE TITLE
关于registerApp方法的参数列表个数问题

### ISSUE THREAD

**Issue by aa494661239** [little-snow-fox/react-native-wechat-lib#25]
我在进行registerApp调用时会报
![image](https://user-images.githubusercontent.com/60681238/73808326-78b19c00-480a-11ea-9771-52d3d8f3d69e.png)

RCTWeChat.registerApp got 2 arguments expected 3

该方法在安卓原生那边确实是接收三个参数

**Comment by loveholly** [comment]
我也遇到了这个问题
```shell
react native version: 0.61.4
react version: 16.9.0
ios version: 13.3
xcode: 11.3 (11C29)
```

**Comment by little-snow-fox** [comment]
@loveholly 这个问题会在本周末进行版本迭代的时候检查一次，或者你可以先尝试切换到 0.60 运行。

**Comment by loveholly** [comment]
请问registerApp的这个问题解决了吗 @little-snow-fox

**Comment by little-snow-fox** [comment]
@loveholly 请问你是不是调用下面方法的时候，universalLink 没传进去？
`WeChat.registerApp('appid', 'universalLink'); `

**Comment by supercharleszhu** [comment]
同样遇到了这个问题，但是不知道universalLink是什么

**Comment by loveholly** [comment]
是我的问题，universalLink没有传正确

**Comment by shucheng7zhong** [comment]
> 是我的问题

请问是怎么解决的

**Comment by kmyw** [comment]
@loveholly 请问怎么解决的

**Comment by kmyw** [comment]
@little-snow-fox 请问作者这个解决了吗 RCTWeChat.registerApp got 2 arguments expected 3

**Comment by jimmywong123** [comment]
> > 是我的问题
> 
> 请问是怎么解决的

appid后面需要接一个universalLink
