### ISSUE TITLE
安卓上调用 WeChat.shareWebpage 返回的 Promise 不会被 resolve

### ISSUE THREAD

**Issue by wong2** [little-snow-fox/react-native-wechat-lib#26]
实际上已经分享成功返回App了，但Promise没有被resolve。iOS是好的

```
const { errCode, errStr } = await WeChat.shareWebpage({
  title,
  description,
  webpageUrl,
  thumbImageUrl,
  scene,
})
```

既没有resolve也没有reject

**Comment by little-snow-fox** [comment]
你好，请问你方便在 android/src/main/java/com/theweflex/react/WeChatModule.java 的 onReq 和 onResp 方法里打个断点吗？

**Comment by wong2** [comment]
@little-snow-fox 我不会 😢

**Comment by wong2** [comment]
@little-snow-fox `onReq`和`onResp`都没有被调用。另外现在我微信登录也出现同样的问题了，之前登录还是好的

**Comment by 369663841** [comment]
@wong2  请问是怎么解决的？ 我现在也有同样的现象，求指点！ 感谢！！

**Comment by wong2** [comment]
@369663841 如果你也是production下面有问题，很可能是代码混淆的问题，可以看看：https://developers.weixin.qq.com/doc/oplatform/Mobile_App/FAQ/Android.html

**Comment by 369663841** [comment]
@wong2  感谢回复！马上试试。

**Comment by hmyjyghh** [comment]
我也遇到这个问题了，iOS 可以执行.then回调, Android 不会执行

**Comment by hmyjyghh** [comment]
WeChat.shareWebpage({
                        title: tempTitle,
                        description: tempDes,
                        thumbImageUrl: previewUrl,
                        webpageUrl,
                        scene: 0
                      })
                        .then(val => {
                          console.log('success:', val)
                          closeEvent(false)
                        })
                        .catch(err => {
                          console.log('errorMsg:', err)
                          closeEvent(false)
                        })
