### ISSUE TITLE
求助！请问怎么使用不包含支付的微信sdk版本?

### ISSUE THREAD

**Issue by weishai** [little-snow-fox/react-native-wechat-lib#27]
我2月16日提交的App审核被拒，说有第三方支付代码，让我解释，我实际用不上微信支付的。
我看到微信开发者中心，有提供不包含支付的sdk版本

## 如何替换微信SDK版本？

**Comment by little-snow-fox** [comment]
你可以从腾讯官方下载 sdk ，然后覆盖到 ios 目录下，这是暂时的解决方案

**Comment by weishai** [comment]
好的，谢谢，我试试更换成最新的1.8.6.2不含支付版

**Comment by liuminghui2017** [comment]
@weishai 我的是android版上传应用宝被拒了，理由是应用包含付费sdk，但android的好像没有不包含支付的sdk，无语了

**Comment by xiaoyhuang123** [comment]
@liuminghui2017 这个后来怎么解决的呢？

**Comment by liuminghui2017** [comment]
@xiaoyhuang123 太久远了，不太记得了，当时好像是应用宝那边不知怎么的把我的app的分类改成游戏类了，然后改回工具类就ok了
