### ISSUE TITLE
【Feature Request】支持一次性订阅消息

### ISSUE THREAD

**Issue by tourze** [little-snow-fox/react-native-wechat-lib#28]
文档地址： https://developers.weixin.qq.com/doc/oplatform/Mobile_App/One-time_subscription_info.html

**Comment by little-snow-fox** [comment]
好，我会排期把该功能加上

**Comment by tourze** [comment]
Thanks♪(･ω･)ﾉ

**Comment by little-snow-fox** [comment]
@tourze 一次性消息订阅接口已经添加到 1.1.13 版本里
