### ISSUE TITLE
1.1.13版本 Android编译报错

### ISSUE THREAD

**Issue by fe-one** [little-snow-fox/react-native-wechat-lib#29]
react-native-wechat-lib/android/src/main/java/com/theweflex/react/WeChatModule.java:525: 错误: 程序包SubscribeMessage不存在
SubscribeMessage.Req req = new SubscribeMessage.Req();

**Comment by wuhuanda** [comment]
@little-snow-fox 提了个PR， #30 PR

**Comment by wuhuanda** [comment]
@fe-one 可以参考一下#30 ，这个主要是少引了一个包

**Comment by little-snow-fox** [comment]
@little-snow-fox 谢谢你的贡献，已经通过合并

**Comment by little-snow-fox** [comment]
@wuhuanda 谢谢你的贡献，已经通过合并
