### ISSUE TITLE
找不到WXApi.h

### ISSUE THREAD

**Issue by willinzhang** [little-snow-fox/react-native-wechat-lib#39]
如果出现报错找不到WXApi、RCTLinkingManager，你需要在Build Settings中添加Header Search Path如下

$(SRCROOT)/../node_modules/react-native-wechat-lib/ios
$(SRCROOT)/../node_modules/react-native/Libraries/LinkingIOS
配置Universal Link，在Xcode的Signing&Capability选项卡中添加Associated Domains，将你选定的域名填进去，必须是https的，然后在微信开放平台中设置UniversalLink，必须与xcode中的一致，universallink设置方法参考苹果的文档和微信的开发者文档
info.plist的LSApplicationQueriesSchemes

按照这个操作做没有作用，我这边是RN0.61.5  没有配置Universal Link，因为老的react-native-wechat是不需要这个参数的

**Comment by little-snow-fox** [comment]
universalLink 必须填写，你填个baidu上去也行。
`WeChat.registerApp('appid', 'universalLink');`

**Comment by willinzhang** [comment]
ok thx
