### ISSUE TITLE
关于Universal Links

### ISSUE THREAD

**Issue by xxj95719** [little-snow-fox/react-native-wechat-lib#4]
没配置Universal Links时，使用不了，后面配了之后，debug可以使用，但是分享都是跳转到朋友圈，且中间会有正在连接小程序的过程，关于这块文档中可以写得更详细一些吗？

**Comment by little-snow-fox** [comment]
出现“正在连接小程序”说明你的APP签名与微信开放平台上面所配置不一致。

**Comment by little-snow-fox** [comment]
如果可以的话，请贴出你的相关代码。

**Comment by EternalChildren** [comment]
同样问题， registerApp方法强制要求Universal Links 这个link是必须配置的吗？

**Comment by little-snow-fox** [comment]
#9
