### ISSUE TITLE
支持0.59版本不?

### ISSUE THREAD

**Issue by xclidongbo** [little-snow-fox/react-native-wechat-lib#40]
支持0.59版本不?

**Comment by xclidongbo** [comment]
iOS 确认都设置完毕. 还是这样报错.

**Comment by little-snow-fox** [comment]
你好，请列出错误信息

**Comment by xclidongbo** [comment]
@little-snow-fox 

Possible Unhandled Promise Rejection (id: 1):
Error: WeChat API invoke returns false.

**Comment by little-snow-fox** [comment]
麻烦贴下调用的代码片段

**Comment by xclidongbo** [comment]
export const shareKit = (shareEnum, shareParams)=>{

  let shareMethod;
  if (shareEnum === ShareEnum.shareWebpage) {
    shareMethod = WeChat.shareWebpage(shareParams)
  } else {
    // shareMethod = WeChat.shareToTimeline(shareParams);
  }
  return new Promise((resolve, reject) => {
    shareMethod.then(res=>{
      console.log('分享成功'); 
      resolve(res);
    }).catch(err=>{
      console.log('分享成功');
      reject(err);
    });
  })
}


shareKit(ShareEnum.shareWebpage, {
                // type: 'news',
                title,
                description: content,
                webpageUrl: url,
                thumbImageUrl: imagePath,
                scene: 0
            });

**Comment by xclidongbo** [comment]
```
export const shareKit = (shareEnum, shareParams)=>{

  let shareMethod;
  if (shareEnum === ShareEnum.shareWebpage) {
    shareMethod = WeChat.shareWebpage(shareParams)
  } else {
    // shareMethod = WeChat.shareToTimeline(shareParams);
  }
  return new Promise((resolve, reject) => {
    shareMethod.then(res=>{
      console.log('分享成功'); 
      resolve(res);
    }).catch(err=>{
      console.log('分享成功');
      reject(err);
    });
  })
}

这样调用的:

shareKit(ShareEnum.shareWebpage, {
                // type: 'news',
                title,
                description: content,
                webpageUrl: url,
                thumbImageUrl: imagePath,
                scene: 0
            });
```

**Comment by xclidongbo** [comment]
我刚看到,你用CallBack来做?

**Comment by little-snow-fox** [comment]
是的，由于目前底层写法问题导致 promise 无法返回成功与否，只能知道执行完成。
要想知道是否成功需要使用 CallBack 来获取回掉事件。

**Comment by xclidongbo** [comment]
WeChat API invoke returns false.那这个错误, 和我采取哪种调用方式没关系吧. 我看了下iOS的配置,都按照这个配置完成了.

**Comment by little-snow-fox** [comment]
成功使用 registerApp 方法注册了吗？

**Comment by xclidongbo** [comment]
RNDataManager.wechatKey().then((res) => {
                WeChat.registerApp(res, 'http://www.baidu.com');
            })

**Comment by little-snow-fox** [comment]
输出下 registerApp 方法的 then 结果

**Comment by xclidongbo** [comment]
稍等...

**Comment by xclidongbo** [comment]
Error: WeChat API invoke returns false.

**Comment by xclidongbo** [comment]
WeChat.registerApp(res, 'http://www.baidu.com',(result)=>{
                    console.log('微信'+result);
                });
这种方式没问题吧?

**Comment by little-snow-fox** [comment]
连注册方法都没法执行，你可能要详细检查一下你的配置，很抱歉我无法准确预估是哪一个配置文件导致

**Comment by xclidongbo** [comment]
好的.

**Comment by xclidongbo** [comment]
@little-snow-fox  支持Cocoapods吗?

**Comment by xclidongbo** [comment]
@little-snow-fox 找到问题了.
```
WeChat.registerApp(res, 'https://www.baidu.com',(result)=>{
                console.log('微信'+result);
            });
```
第二个通用URL的参数必须是https格式.
