### ISSUE TITLE
sendAuthRequest返回没有获取到openid

### ISSUE THREAD

**Issue by huiyejiawang** [little-snow-fox/react-native-wechat-lib#43]
`WeChat.sendAuthRequest('snsapi_userinfo')
      .then(result => {
        console.log('wechat:sendAuthRequest : ', result)
      })
      .catch(e => console.log('wechat_err:sendAuthRequest()', e));`

返回的result里，没有openid

**Comment by little-snow-fox** [comment]
需要使用订阅事件来获取返回值
请查看新添加的 [回调事件订阅例子](https://github.com/little-snow-fox/react-native-wechat-lib#%E8%AE%A2%E9%98%85%E5%9B%9E%E8%B0%83%E4%BA%8B%E4%BB%B6)

**Comment by zhangyanlf** [comment]
登录授权回调也需要添加订阅来获取返回值吗 ？

**Comment by zhangyanlf** [comment]
微信登录授权sendAuthRequest   没有回调  添加订阅事件也没有回调 是什么原因 ？

**Comment by qilovehua** [comment]
我的返回code，openid是空字符串
你们能直接拿到openid？

**Comment by huiyejiawang** [comment]
> 我的返回code，openid是空字符串
> 你们能直接拿到openid？

能拿到code，直接从js发起access_token了，这样获取了openid
