### ISSUE TITLE
登录授权sendAuthRequest 没有回调 添加订阅事件也没有回调 是什么原因 ？

### ISSUE THREAD

**Issue by zhangyanlf** [little-snow-fox/react-native-wechat-lib#44]
@little-snow-fox

**Comment by little-snow-fox** [comment]
请提供下设备信息和相关代码

**Comment by zhangyanlf** [comment]
设备信息 iPhone11   13.4
react-native：0.61.5
------------------------------------
iOS  AppDelegate
- (BOOL)application:(UIApplication *)application handleOpenURL:(NSURL *)url {
    return  [WXApi handleOpenURL:url delegate:self];
}

- (BOOL)application:(UIApplication *)application
  continueUserActivity:(NSUserActivity *)userActivity
  restorationHandler:(void(^)(NSArray<id<UIUserActivityRestoring>> * __nullable
  restorableObjects))restorationHandler {
  // 触发回调方法
  [RCTLinkingManager application:application continueUserActivity:userActivity restorationHandler:restorationHandler];
  return [WXApi handleOpenUniversalLink:userActivity delegate:self];
}


RN -----------
_weChatLogin(){ //微信登录
        let scope = 'snsapi_userinfo'; 
        let state = 'raise_funds'; 
        //判断微信是否安装
        WeChat.isWXAppInstalled()
            .then((isInstalled) => {
                if (isInstalled) {
                    WeChat.sendAuthRequest(scope,state)
                        .then(responseCode => {
                            this.getOpenId(responseCode);
                        })
                        .catch(err => {
                            alert('登录授权发生错误：', err.message);
                        })
                } else {
                    alert('没有安装微信，请先安装微信客户端在进行登录');
                }
            })


    }

**Comment by little-snow-fox** [comment]
DeviceEventEmitter.addListener 方法呢？需要使用 DeviceEventEmitter 来设置回调事件。

**Comment by zhangyanlf** [comment]
我在AppDelegate  添加方法  获取到回调了
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
            options:(NSDictionary<NSString*, id> *)options
{
  // Triggers a callback event.
  // 触发回调事件
  [RCTLinkingManager application:application openURL:url options:options];
  return [WXApi handleOpenURL:url delegate:self];
}

**Comment by little-snow-fox** [comment]
openURL 的方法必须使用 Universal Links 来进行回调，请问你的 Universal Links 是否正常可用？例如在 safari 输入 URL 能出现跳转 APP 的提示吗？

**Comment by zhangyanlf** [comment]
Universal Links 我是随便填的地址  safari输入 URL 不能出现跳转 APP 的提示，但是可以获取都回调，当在开发模式没问题  到了生产模式就会出现问题？ 是这样吗 ？

**Comment by little-snow-fox** [comment]
没错，实际上触发回调有两种方式，openURL 是其中一种，它只提供 Universal Links 方式调用，如果你地址是随便添，微信就没法重新拉起你的 APP，更没可能触发回调，详细请查看 [IOS 文档](https://github.com/little-snow-fox/react-native-wechat-lib/blob/master/docs/build-setup-ios.md#2-then-copy-the-following-in-appdelegatem)

**Comment by ftmacb** [comment]
你好，我也遇到同样的问题，跟楼主的环境、设备也一样。我设置了正确的Universal Links，微信登录授权之后也能重新拉起我的App，但是会停留在启动页一段时间，然后就崩掉了。sendAuthRequest也没有回调，添加订阅事件也没有回调，请问是什么问题呢？ @little-snow-fox

**Comment by syd24** [comment]
请问这个url具体是啥啊？我在safari浏览器输入完整的url（例如：https://www.baidu.com/apple-app-site-association），只会下载这个文件并不会跳转app，说明我的Universal Links有问题吗？
