### ISSUE TITLE
React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by tanhao8** [little-snow-fox/react-native-wechat-lib#46]
React/RCTBridgeModule.h' file not found

**Comment by JohnSmith0602** [comment]
今天安装碰到同样的问题，而且在网上查了相关的问题会指向 [react Scheme missing](https://github.com/facebook/react-native/issues/25838#issuecomment-517894895)，但是我的 build scheme 里是有 React，也会报这个错。

然后我直接把 #import <React/RCTBridgeDelegate.h> 这一行给删掉了，似乎还是可以工作的。所以 React/RCTBridgeModule.h 是必须的吗？

**Comment by kuaile123go** [comment]
我从0.59升级到0.61也碰到这个问题

**Comment by guyue88** [comment]
@little-snow-fox  所以解决方案是什么？

**Comment by little-snow-fox** [comment]
> @little-snow-fox 所以解决方案是什么？

请尝试使用最新的 3.0.x 版本，如再次遇到该问题，请开启新的问题，并附上错误信息和系统信息版本号，我会关注
