### ISSUE TITLE
release 模式调起微信后直接返回APP，没有任何响应，直到超时

### ISSUE THREAD

**Issue by yiluzhang** [little-snow-fox/react-native-wechat-lib#48]
版本：1.1.16
微信版本：7.0.12
debug 模式下一切正常。
release 模式下调起微信后直接返回APP，没有任何响应，直到超时报错

` finished with error [-1001] Error Domain=NSURLErrorDomain Code=-1001 "The request timed out." 

UserInfo={_kCFStreamErrorCodeKey=60, NSUnderlyingError=0x2806eaa60 {Error Domain=kCFErrorDomainCFNetwork Code=-1001 "(null)" UserInfo={_kCFStreamErrorCodeKey=60, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <38FF3F67-8F2B-45C6-80F0-5F04AC93B979>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <38FF3F67-8F2B-45C6-80F0-5F04AC93B979>.<1>"
), NSLocalizedDescription=The request timed out., NSErrorFailingURLStringKey=https://clients3.google.com/generate_204, NSErrorFailingURLKey=https://clients3.google.com/generate_204, _kCFStreamErrorDomainKey=1}`

**Comment by little-snow-fox** [comment]
请问是 Android 还是 IOS 平台？

**Comment by yiluzhang** [comment]
> 请问是 Android 还是 IOS 平台？

iOS，Android没有问题。
应该是Universal Links的问题。重新部署了Universal Links真机release测试通过。
