### ISSUE TITLE
Can I delete the comments about uiwebview? IOS store can't submit them

### ISSUE THREAD

**Issue by zj799072102** [little-snow-fox/react-native-wechat-lib#51]
ITMS-90809: Deprecated API Usage - New apps that use UIWebView are no longer accepted. Instead, use WKWebView for improved security and reliability. Learn more (https://developer.apple.com/documentation/uikit/uiwebview).

**Comment by little-snow-fox** [comment]
Hello, WKWebView cannot be searched in the code because it has been removed, please check if it is caused by other libraries.

**Comment by zj799072102** [comment]
I have found the reason. The SDK version of our library is too low. It contains uiwebview, so we need to upgrade the SDK
