### ISSUE TITLE
RCTWeChat.registerApp got 2 arguments,expected 3

### ISSUE THREAD

**Issue by fuyue111** [little-snow-fox/react-native-wechat-lib#53]
![image](https://user-images.githubusercontent.com/19793236/81467749-654d0d00-920d-11ea-93da-84abcb1000d5.png)
registerApp 报错，有看到@loveholly的提问，看起来还没修复？

**Comment by Beats0** [comment]
测了一下，貌似在iphoneX以下正常，phoneX以上就会出现这个问题

**Comment by caowei121** [comment]
什么原因呢
