### ISSUE TITLE
不支持 RN 0.58？

### ISSUE THREAD

**Issue by GreatAuk** [little-snow-fox/react-native-wechat-lib#54]
目前 RN 版本0.58.6 ， android 打包报错
![image](https://user-images.githubusercontent.com/20253809/81548464-f0660880-93af-11ea-8a12-9f858cc3f383.png)
应该是因为 0.58 的版本还不支持 AndroidX，目前处理上是把 `Nullable` 相关的代码都删了，如：public void invoke(@Nullable Bitmap bitmap)  =>  public void invoke(Bitmap bitmap)

目前打包是不报错了。因为不会`android`开发，不太清楚是否会影响代码的正常运行

**Comment by kingsword09** [comment]
`
// import androidx.annotation.Nullable;
import android.support.annotation.Nullable;
`
我把androidx注释掉，换support就可以了

**Comment by kingsword09** [comment]
`//import androidx.annotation.Nullable;`
`import android.support.annotation.Nullable;`
我是注释掉androidx，换support就可以了
