### ISSUE TITLE
Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_WKWebView", referenced from:       objc-class-ref in libWeChatSDK.a(WapAuthHandler.o) ld: symbol(s) not found for architecture arm64

### ISSUE THREAD

**Issue by lidiwen** [little-snow-fox/react-native-wechat-lib#57]
x-code 该配的配置都加了 还是会遇到这个问题。两天了还没解决

**Comment by cshung1994** [comment]
How to fix this?

**Comment by jimmywong123** [comment]
同问题，请问怎样解决的？

**Comment by jimmywong123** [comment]
在这篇链接里找到了解决方法
https://blog.csdn.net/wanglei0918/article/details/78468070

**Comment by cshung1994** [comment]
This is not work for me.

**Comment by LHJ-K2S** [comment]
react-native-wechat-lib/RCTWeChat.podspec里，s.frameworks = 'SystemConfiguration','CoreTelephony'后面添加'WebKit'
