### ISSUE TITLE
微信支付 ios正常，android支付完成后，点击返回商家app闪退

### ISSUE THREAD

**Issue by Miluaaa** [little-snow-fox/react-native-wechat-lib#60]
"react-native-wechat-lib": "^1.1.16",
"react": "16.9.0",
"react-native": "0.61.5",

**Comment by jmy10241024** [comment]
俺也一样

**Comment by Miluaaa** [comment]
> 俺也一样

在新建的两个文件里 包名后面加.wxapi了吗

package 你的包名 + .wxapi

**Comment by jptwl** [comment]
我也一样……不止是支付……登录回调也闪退
