### ISSUE TITLE
关于SDK版本问题

### ISSUE THREAD

**Issue by kmyw** [little-snow-fox/react-native-wechat-lib#62]
麻烦作者大佬，有空更新一下，微信sdk版本，ios分享图片有的机型会报未验证应用，查了下是微信sdk没有最新的原因，目前微信最新sdk，ios：1.8.7.1, android: 6.6.4 @little-snow-fox

**Comment by swplzj** [comment]
遇到同样的问题了，使用版本1.1.16，iOS13.5 测试设备，但还出现“未验证应用”，希望作者大佬及时升级，非常感谢 @little-snow-fox

**Comment by little-snow-fox** [comment]
好的，我会在下周更新一下 SDK 版本，你们可以暂时从官网下载 SDK 然后覆盖到相应位置

**Comment by little-snow-fox** [comment]
IOS 的 SDK 版本已经更新到 1.8.7.1，并且添加了不需要使用支付功能的 SDK 版本 [附言](https://github.com/little-snow-fox/react-native-wechat-lib)

**Comment by orzhtml** [comment]
该问题解决了么？

**Comment by chenweigh** [comment]
我按照微信官方文档、苹果文档配置了 universal link , 但是配置的 `universal link` 在 Safari 中是 404， 不知道是不是因为这个原因导致未验证呀？

首次分享的时候，有正在连接页面，后续就没有了。
环境： `react-native-wechat-lib:1.1.22 `

**Comment by chenweigh** [comment]
> 我按照微信官方文档、苹果文档配置了 universal link , 但是配置的 `universal link` 在 Safari 中是 404， 不知道是不是因为这个原因导致未验证呀？
> 
> 首次分享的时候，有正在连接页面，后续就没有了。
> 环境： `react-native-wechat-lib:1.1.22 `

我错了，那个 404 是我们服务器的，最上面有在那个打开的提示视图

**Comment by chenweigh** [comment]
Universal Links在系统自带的浏览器可以打开app在备忘录中也可以打开app，分享登录的跳转也正确，但是分享到微信还是显示（未验证应用），楼主知道改怎么解决吗？微信官方那里也没人解答

**Comment by chj-damon** [comment]
@chenweigh 遇到一样的问题，请问你解决了吗

**Comment by chenweigh** [comment]
还没发自我的华为手机-------- 原始邮件 --------发件人： "damon.chen" <notifications@github.com>日期： 2020年9月21日周一 15:03收件人： little-snow-fox/react-native-wechat-lib <react-native-wechat-lib@noreply.github.com>抄送： Eleven <chen158_7@126.com>, Mention <mention@noreply.github.com>主    题： Re: [little-snow-fox/react-native-wechat-lib] 关于SDK版本问题 (#62)

@chenweigh 遇到一样的问题，请问你解决了吗
