### ISSUE TITLE
使用方法launchMiniProgram，能跳到微信，但是不能打开小程序，是为什么呢

### ISSUE THREAD

**Issue by iamfindingway** [little-snow-fox/react-native-wechat-lib#65]

**Comment by iamfindingway** [comment]
![图片](https://user-images.githubusercontent.com/37784114/84991931-c1467200-b179-11ea-8d1b-4edb8d5b1c08.png)
出现这个页面，然后这个页面消失，停留在微信里，不会跳转微信

**Comment by little-snow-fox** [comment]
请检查你的 universalLink 是否配置正确

**Comment by iamfindingway** [comment]
@little-snow-fox 我解决了，是因为手机里有别的app里的appId跟我的冲突了，导致从微信跳不回原来的app，把导致冲突的app卸载掉就可以了
