### ISSUE TITLE
ios wechat api invoke returns false

### ISSUE THREAD

**Issue by xuqianjin** [little-snow-fox/react-native-wechat-lib#7]
ios下所有wechat api都报这个错误..是缺少什么配置吗

**Comment by ihwf** [comment]
同样遇到这个问题, 请问怎么解决?

**Comment by little-snow-fox** [comment]
@ihwf 遇到这个错误是因为环境没配置好，请按照文档再检查一次，特别是URL Schema这一块。

**Comment by ihwf** [comment]
OK, 确实是配置问题, 感谢👍

**Comment by ihwf** [comment]
OK, 确实是配置问题, 感谢👍

**Comment by chj-damon** [comment]
我按照ios的readme配置好了，在registerApp的时候universalLinks也填了，但是还是报这个错。
