### ISSUE TITLE
发现一处文档错误，期待修订

### ISSUE THREAD

**Issue by PBK-B** [little-snow-fox/react-native-wechat-lib#75]
在使用 ShareWebpage (ShareWebpageMetadata) 分享网页接口时发现文档有一点小瑕疵

![屏幕快照 2020-07-15 上午9 32 05](https://user-images.githubusercontent.com/39079814/87497318-e7cbd000-c687-11ea-8a3a-60471f6fd070.png)

**Comment by little-snow-fox** [comment]
好的

**Comment by jameszhan02** [comment]
2022年了，改了吧🐶

> 好的
