### ISSUE TITLE
无法分享小程序测试版或者开发版

### ISSUE THREAD

**Issue by MrLaibin** [little-snow-fox/react-native-wechat-lib#76]
js端：shareMiniProgram
android端:miniprogramType
大小写不同，无法获取到js端传来的输送

**Comment by MrLaibin** [comment]
已pull request

**Comment by gaothing** [comment]
这个是已经解决了吗

**Comment by MrLaibin** [comment]
> 这个是已经解决了吗

是的，当时能用的。现在没做RN项目了，不清楚现在情况了
