### ISSUE TITLE
微信支付的参数少了appId

### ISSUE THREAD

**Issue by chj-damon** [little-snow-fox/react-native-wechat-lib#79]
![image](https://user-images.githubusercontent.com/4902684/88132912-4dcdcf80-cc13-11ea-9ba4-8f2c6c32d061.png)
文档地址：https://pay.weixin.qq.com/wiki/doc/api/app/app.php?chapter=9_12&index=2
现在Wechat.pay的参数定义是：
```ts
export interface PaymentLoad {
    partnerId: string;
    prepayId: string;
    nonceStr: string;
    timeStamp: string;
    package: string;
    sign: string;
  }
  export function pay(
    payload: PaymentLoad
  ): Promise<{ errCode?: number; errStr?: string }>;
```

问题1：少了appId
问题2：是否需要区分大小写

**Comment by chj-damon** [comment]
看了源码，没问题。

**Comment by Zhou-Bill** [comment]
这个appid 是在register的时候就添加上，还是怎么的？？

**Comment by insistentSnail** [comment]
登录时的appid和支付时的应该不是同一个、直接用登录的appid 会提示 商户传入的appid参数不正确，请问您是怎么处理的

**Comment by luckyGTL** [comment]
> 登录时的appid和支付时的应该不是同一个、直接用登录的appid 会提示 商户传入的appid参数不正确，请问您是怎么处理的

请问你解决了吗

**Comment by newyoung21** [comment]
> > 登录时的appid和支付时的应该不是同一个、直接使用登录的appid 会提示 商家传入的appid参与次数不正确，请问您是怎么​​处理的
> 
> 请问你解决了吗

请问解决了吗？

**Comment by luckyGTL** [comment]
我这边解决了。确实是因为appid和商户id对应的appid不匹配导致的。
