### ISSUE TITLE
This app is not allowed to query for scheme weixinulapi during sendAuthRequest

### ISSUE THREAD

**Issue by enigmablue** [little-snow-fox/react-native-wechat-lib#86]
I am having this issue when i try to do an authRequest. Anyone have suggestion?

-canOpenURL: failed for URL: "weixinULAPI://" - error: "This app is not allowed to query for scheme weixinulapi"

i double checked that i dont have this error when i try the yorkie package of wechat. (But i have another problem there where after accepting approval in wechat, there is no callback)

 ```
 let scope = 'snsapi_userinfo';
     let state = 'wechat_sdk_demo';
     //判断微信是否安装
     WeChat.isWXAppInstalled()
       .then((isInstalled) => {
         if (isInstalled) {
           //发送授权请求
           console.log("sending auth request for scope ", scope)
           WeChat.sendAuthRequest(scope, state)
             .then(responseCode => {
               //返回code码，通过code获取access_token
               getAccessToken(responseCode.code);
             })
             .catch(err => {
               Alert.alert('登录授权发生错误：', err.message, [
                 {text: '确定'}
               ]);
             })
```

**Comment by caowei121** [comment]
你好，我也是同意后授权没有回调和任何参数返回，你是怎么解决的呢

**Comment by enigmablue** [comment]
If you see the instructions https://github.com/little-snow-fox/react-native-wechat-lib/blob/master/docs/build-setup-ios.md

This is needed in the info.plist
<key>LSApplicationQueriesSchemes</key>
<array>
  <string>weixin</string>
  <string>wechat</string>
  <string>weixinULAPI</string>
</array>
