### ISSUE TITLE
RN 60 版本后还需要link吗？

### ISSUE THREAD

**Issue by UtillYou** [little-snow-fox/react-native-wechat-lib#87]
RN 60 版本都是自动link的，在这种情况下还需要运行 `react-native link react-native-wechat-lib`  和手动添加 `MainActivity.java` 中的代码吗？

**Comment by skychx** [comment]
> RN 60 版本都是自动link的，在这种情况下还需要运行 `react-native link react-native-wechat-lib` 和手动添加 `MainActivity.java` 中的代码吗？

不需要，iOS 直接 `cd ios`，然后 `pod install` 就可以；Android 直接 `gradle sync` 就可以了
