### ISSUE TITLE
registerApp是强制要求universalLink？

### ISSUE THREAD

**Issue by EternalChildren** [little-snow-fox/react-native-wechat-lib#9]
1.  registerApp 是强制要求 universalLink 吗 如果没写会抛出异常，状态如下
```
{ [Error: WeChat API invoke returns false.]
  line: 116691,
  column: 36,
  sourceURL: 'http://192.168.2.13:8081/index.bundle?platform=ios&dev=true&minify=false' },
```
2. 如果没注册成功会导致其他api都没法正常调用， 这个应该是正常的，但是出错了缺没有将错误抛出，导致js层没法处理异常，如关闭Loading层。

而且我建议重新封装js层来更加友好的抛出异常， 更好的回馈不应该是由errCode来决定成功和失败， 而是成功就是顺利执行， 失败则是抛到异常层 （如果需要的话，我可以帮忙封装RN对接层）
看好这个库  之前的react-native-wechat真的太老了

**Comment by little-snow-fox** [comment]
在 IOS 上，universalLink 必须填写，因为 WeChat SDK 需要它，你可以乱填一个合法的网址格式。
关于这个错误提示，确实需要要很好地处理，不过头疼的是 WeChat SDK 不会提供具体错误内容，只返回了 true 和 flase。
如果你愿意参与进来就太好了。

**Comment by c78867886** [comment]
> 在 IOS 上，universalLink 必须填写，因为 WeChat SDK 需要它，你可以乱填一个合法的网址格式。
> 关于这个错误提示，确实需要要很好地处理，不过头疼的是 WeChat SDK 不会提供具体错误内容，只返回了 true 和 flase。
> 如果你愿意参与进来就太好了。

如果只是要開啟微信然後分享到好友圈而已
universal link可以亂填是嗎？
只要保持跟微信公開平台上 註冊app時填的一致就可以了？

**Comment by scgy5555** [comment]
踩坑了，安卓不会因为universalLink而初始化失败，ios中必填
只要没有初始化成功 registerApp 无法调用 所有sdk api都失效
