### ISSUE TITLE
请问，没有merge进 react-native-wechat 是什么问题呢？接口breaking change太多了？

### ISSUE THREAD

**Issue by JTangming** [little-snow-fox/react-native-wechat-lib#93]
对于使用react-native-wechat的应用有点难受，如果使用作者这个lib，业务层代码变动大多。

所以就有了title的问题 /笑哭，或者其他使用react-native-wechat的用户，都是怎么解决问题的，如不接入新的OpenSDK（1.8.6 +）则在iOS分享显示“未验证应用”。

**Comment by little-snow-fox** [comment]
很抱歉，就是因为 react-native-wechat-lib 无法与 react-native-wechat 兼容所以才会开启一个新的项目，之前给 react-native-wechat-lib 仓库提交过一个大版本更新，但由几乎重写一样的代码变动所以无法合并。
