### ISSUE TITLE
有没有计划封装下发票业务的api?

### ISSUE THREAD

**Issue by xclidongbo** [little-snow-fox/react-native-wechat-lib#96]
WXChooseCardReq

**Comment by little-snow-fox** [comment]
麻烦提供一下该功能在微信开放平台的文档地址

**Comment by hengkx** [comment]
https://developers.weixin.qq.com/doc/offiaccount/WeChat_Invoice/E_Invoice/Vendor_API_List.html#4

**Comment by hengkx** [comment]
https://developers.weixin.qq.com/doc/offiaccount/WeChat_Invoice/E_Invoice/Reimburser_API_List.html#4
这个

**Comment by xclidongbo** [comment]
@little-snow-fox 感谢一直维护,虽然没升级到最新版, 我们原生自己实现了发票的api调用. 不过拖欠的咖啡钱你得收下.

**Comment by xclidongbo** [comment]
关闭了关闭了.

**Comment by little-snow-fox** [comment]
> @little-snow-fox 感谢一直维护,虽然没升级到最新版, 我们原生自己实现了发票的api调用. 不过拖欠的咖啡钱你得收下.

感谢你的支持
